#!/usr/bin/env python
#
# Copyright (c) Paul Tagliamonte
# GNU GPL-3+, 2011
#

from optparse import OptionParser
import Syn.common as c
import Syn.Global as g
import Syn.s      as syn
import Syn.log

parser = OptionParser()

parser.add_option("-i", "--info",
	dest  = "info",  help = "Get metadata info on the package")

parser.add_option("-b", "--build",
	dest  = "build", help = "Build the syn source file")

(options, args) = parser.parse_args()

attrs = [
	"package",
	"version",
	"description",
	"homepage",
	"maintainer",
	"deps",
]

try:
	if options.info != None:
		meta = syn.metadump(options.info)
		for attr in attrs:
			if isinstance(meta[attr], list):
				print attr + ":	"
				for x in meta[attr]:
					print "  " + str(x)
			elif isinstance(meta[attr], dict):
				print attr + ":	"
				for x in meta[attr]:
					print "  " + str(meta[attr][x])
			else:
				print attr + ":	" + meta[attr]

except NameError:
	pass

try:
	if options.build != None:
		syn.buildFromSource(options.build)
except NameError:
	pass

