#!/usr/bin/env python

import Syn
from Syn import output, setup, constants, tools, errors
import os

try:
	dirz = setup.importFromURL( "http://ftp.gnu.org/gnu/bash/bash-3.2.tar.gz" )

	if dirz:
		print "Downloaded everything to `" + dirz + "`"

except KeyboardInterrupt:
	print ""
	print "  Jesus, calm down. Don't be a dick about it."
except errors.ShittyConfException as e:
	print ""
	print "Make sure you have a synrc file that is, you know, right."
	print "Error: " + str(e)
