#!/bin/bash

if [ -e *deb ]; then
	rm *deb
fi

if [ -d syn ]; then
	rm -rf syn
fi

apt-get download $1
mkdir syn
dpkg-deb -x *.deb syn/
metainf=`dpkg-deb -I *.deb`

descr=`echo "$metainf"    | grep Description      | sed s/\ Description:\ //g`
maint=`echo "$metainf"    | grep Maintainer:      | sed s/\ Maintainer:\ //g`
pkg=`echo "$metainf"      | grep Package:         | sed s/\ Package:\ //g`
ver=`echo "$metainf"      | grep Version:         | sed s/\ Version:\ //g`
deps=`echo "$metainf"     | grep ^\ Depends:\     | sed s/\ Depends:\ //g     | sed -r 's/\(.[^)]*\)//g' | sed s/[\ ]*//g`
predeps=`echo "$metainf"  | grep ^\ Pre-Depends:\ | sed s/\ Pre-Depends:\ //g | sed -r 's/\(.[^)]*\)//g' | sed s/[\ ]*//g`
email=`echo $maint        | sed s/.*\<//g         | tr -d ">"`
name=`echo $maint         | sed s/\<.*\>//g`

if [ "x$predeps" != "x" ]; then
	# echo " Deps: Both pre and post root"
	deps="$deps,$predeps"
fi

JSONDeps="[\"`echo "$deps" | sed s/,/\\\",\\\"/g`\"]"

echo "Descr: $descr"
echo "Maint: $maint"
echo " Name: $name"
echo "Email: $email"
echo "Packg: $pkg"
echo "Versn: $ver"
echo " Deps: $JSONDeps"
