WORKDIR = "/tmp/syn/"

DEFAULT_SYN   = "~/.syn/"
DEFAULT_SYNRC = DEFAULT_SYN + "synrc"

SYN_BUILDDIR        = "synd/"
SYN_BUILDDIR_SCRIPT = "build"
SYN_BUILDDIR_CONFIG = "buildrc"
SYN_BUILDDIR_META   = "meta"

CONFIG_FLAGS = "CONFIG_FLAGS"
BUILD_FLAGS  = "BUILD_FLAGS"
STAGE_FLAGS  = "STAGE_FLAGS"

CONFIG       = "CONFIGURE"
BUILD        = "BUILD"
STAGE        = "STAGE"

DESTDIR      = "S_DESTDIR"

ARCHIVE_FS_ROOT = "syn"
BUILD_FS_ROOT   = "build"
